import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
    MessageSquare, CreditCard, Phone, FileText, Download, Webhook,
    Loader2, Check, Copy, Send, Image, Bot, Database, UserPlus, Users, Mail, Volume2
} from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function TestFunctions() {
    const [loading, setLoading] = useState('');
    const [result, setResult] = useState(null);
    const [copied, setCopied] = useState(false);

    // OpenAI Chat test
    const [chatPrompt, setChatPrompt] = useState('');
    
    // SMS test
    const [smsTo, setSmsTo] = useState('');
    const [smsBody, setSmsBody] = useState('');
    
    // PDF test
    const [pdfTitle, setPdfTitle] = useState('Test Report');
    const [pdfContent, setPdfContent] = useState('This is a test PDF document generated by 1cPublishing.');
    
    // Invite user test
    const [inviteEmail, setInviteEmail] = useState('');
    const [inviteFullName, setInviteFullName] = useState('');
    const [inviteRole, setInviteRole] = useState('user');
    
    // Email test
    const [emailTo, setEmailTo] = useState('');
    const [emailSubject, setEmailSubject] = useState('');
    const [emailBody, setEmailBody] = useState('');

    const runTest = async (testName, fn) => {
        setLoading(testName);
        setResult(null);
        try {
            const response = await fn();
            setResult({ success: true, data: response.data });
        } catch (error) {
            setResult({ success: false, error: error.message });
        } finally {
            setLoading('');
        }
    };

    const copyResult = () => {
        navigator.clipboard.writeText(JSON.stringify(result, null, 2));
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="p-6 max-w-6xl mx-auto">
            <div className="mb-8">
                <h1 className="text-3xl font-bold text-gray-900 mb-2">Backend Functions Test</h1>
                <p className="text-gray-600">Test all available backend functions for your enterprise app</p>
            </div>

            <Tabs defaultValue="openai" className="space-y-6">
                <TabsList className="grid grid-cols-9 w-full">
                    <TabsTrigger value="openai" className="gap-2"><Bot className="w-4 h-4" /> OpenAI</TabsTrigger>
                    <TabsTrigger value="elevenlabs" className="gap-2"><Volume2 className="w-4 h-4" /> ElevenLabs</TabsTrigger>
                    <TabsTrigger value="stripe" className="gap-2"><CreditCard className="w-4 h-4" /> Stripe</TabsTrigger>
                    <TabsTrigger value="twilio" className="gap-2"><Phone className="w-4 h-4" /> Twilio</TabsTrigger>
                    <TabsTrigger value="email" className="gap-2"><Mail className="w-4 h-4" /> Email</TabsTrigger>
                    <TabsTrigger value="pdf" className="gap-2"><FileText className="w-4 h-4" /> PDF</TabsTrigger>
                    <TabsTrigger value="export" className="gap-2"><Download className="w-4 h-4" /> Export</TabsTrigger>
                    <TabsTrigger value="webhook" className="gap-2"><Webhook className="w-4 h-4" /> Webhooks</TabsTrigger>
                    <TabsTrigger value="users" className="gap-2"><Users className="w-4 h-4" /> Users</TabsTrigger>
                </TabsList>

                {/* OpenAI Tab */}
                <TabsContent value="openai" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <MessageSquare className="w-5 h-5 text-purple-600" />
                                GPT-4 Chat
                            </CardTitle>
                            <CardDescription>Test OpenAI chat completions with GPT-4</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Textarea
                                value={chatPrompt}
                                onChange={(e) => setChatPrompt(e.target.value)}
                                placeholder="Enter your prompt..."
                                className="min-h-[100px]"
                            />
                            <Button
                                onClick={() => runTest('chat', () => 
                                    base44.functions.invoke('openaiChat', { 
                                        prompt: chatPrompt,
                                        model: 'gpt-4o-mini'
                                    })
                                )}
                                disabled={loading === 'chat' || !chatPrompt}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'chat' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Send className="w-4 h-4 mr-2" />}
                                Send to GPT-4
                            </Button>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <Database className="w-5 h-5 text-purple-600" />
                                Embeddings
                            </CardTitle>
                            <CardDescription>Generate text embeddings for semantic search</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Button
                                onClick={() => runTest('embeddings', () => 
                                    base44.functions.invoke('openaiEmbeddings', { 
                                        texts: ['Hello world', 'Machine learning is fascinating']
                                    })
                                )}
                                disabled={loading === 'embeddings'}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'embeddings' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                                Generate Embeddings
                            </Button>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* ElevenLabs Tab */}
                <TabsContent value="elevenlabs" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <Volume2 className="w-5 h-5 text-purple-600" />
                                ElevenLabs TTS API Test
                            </CardTitle>
                            <CardDescription>Test your ElevenLabs API key and subscription status</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Button
                                onClick={async () => {
                                    setLoading('elevenlabs-test');
                                    setResult(null);
                                    try {
                                        const response = await base44.functions.invoke('elevenlabsTTS', { test: true });
                                        setResult({ success: true, data: response.data });
                                    } catch (error) {
                                        setResult({ success: false, error: error.response?.data?.error || error.message });
                                    } finally {
                                        setLoading('');
                                    }
                                }}
                                disabled={loading === 'elevenlabs-test'}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'elevenlabs-test' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Check className="w-4 h-4 mr-2" />}
                                Test API Key & Subscription
                            </Button>
                            <p className="text-sm text-gray-500">
                                This will verify your ElevenLabs API key and show your subscription status including character usage.
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>Generate Speech</CardTitle>
                            <CardDescription>Test text-to-speech generation</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Textarea
                                id="tts-text"
                                placeholder="Enter text to convert to speech..."
                                className="min-h-[100px]"
                                defaultValue="Hello, this is a test of the ElevenLabs text to speech system."
                            />
                            <Select defaultValue="EXAVITQu4vr4xnSDxMaL">
                                <SelectTrigger id="tts-voice">
                                    <SelectValue placeholder="Select voice" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="EXAVITQu4vr4xnSDxMaL">Bella</SelectItem>
                                    <SelectItem value="21m00Tcm4TlvDq8ikWAM">Rachel</SelectItem>
                                    <SelectItem value="AZnzlk1XvdvUeBnXmlld">Domi</SelectItem>
                                    <SelectItem value="MF3mGyEYCl7XYWbV9V6O">Elli</SelectItem>
                                </SelectContent>
                            </Select>
                            <Button
                                onClick={async () => {
                                    setLoading('elevenlabs-tts');
                                    setResult(null);
                                    try {
                                        const text = document.getElementById('tts-text').value;
                                        const voice = document.getElementById('tts-voice')?.querySelector('[data-value]')?.dataset?.value || 'EXAVITQu4vr4xnSDxMaL';
                                        const response = await base44.functions.invoke('elevenlabsTTS', {
                                            text,
                                            voice_id: voice
                                        });
                                        if (response.data?.audio) {
                                            // Play audio
                                            const binaryString = atob(response.data.audio);
                                            const bytes = new Uint8Array(binaryString.length);
                                            for (let i = 0; i < binaryString.length; i++) {
                                                bytes[i] = binaryString.charCodeAt(i);
                                            }
                                            const blob = new Blob([bytes], { type: 'audio/mpeg' });
                                            const audioUrl = URL.createObjectURL(blob);
                                            const audio = new Audio(audioUrl);
                                            audio.play();
                                            setResult({ success: true, data: { message: 'Audio playing!', bytes: bytes.length } });
                                        } else {
                                            setResult({ success: false, data: response.data });
                                        }
                                    } catch (error) {
                                        setResult({ success: false, error: error.message });
                                    } finally {
                                        setLoading('');
                                    }
                                }}
                                disabled={loading === 'elevenlabs-tts'}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'elevenlabs-tts' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Volume2 className="w-4 h-4 mr-2" />}
                                Generate & Play Speech
                            </Button>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* Stripe Tab */}
                <TabsContent value="stripe" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle>Stripe Payments</CardTitle>
                            <CardDescription>Create payment intents and checkout sessions</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Button
                                onClick={() => runTest('customer', () => 
                                    base44.functions.invoke('stripePayments', { action: 'createCustomer' })
                                )}
                                disabled={loading === 'customer'}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'customer' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                                Create Customer
                            </Button>
                            <Button
                                onClick={() => runTest('checkout', () => 
                                    base44.functions.invoke('stripePayments', { 
                                        action: 'createCheckoutSession',
                                        amount: 29.99,
                                        description: 'Test Product'
                                    })
                                )}
                                disabled={loading === 'checkout'}
                                variant="outline"
                            >
                                {loading === 'checkout' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                                Create Checkout Session
                            </Button>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>Subscriptions</CardTitle>
                            <CardDescription>Manage recurring billing and subscriptions</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <p className="text-sm text-gray-500 mb-4">
                                Use stripeSubscriptions function with actions: createProduct, createSubscription, cancelSubscription, etc.
                            </p>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* Twilio Tab */}
                <TabsContent value="twilio" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle>SMS Messaging</CardTitle>
                            <CardDescription>Send SMS messages via Twilio</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Input
                                value={smsTo}
                                onChange={(e) => setSmsTo(e.target.value)}
                                placeholder="Phone number (e.g., +1234567890)"
                            />
                            <Textarea
                                value={smsBody}
                                onChange={(e) => setSmsBody(e.target.value)}
                                placeholder="Message body..."
                            />
                            <Button
                                onClick={() => runTest('sms', () => 
                                    base44.functions.invoke('twilioSms', { 
                                        action: 'send',
                                        to: smsTo,
                                        body: smsBody
                                    })
                                )}
                                disabled={loading === 'sms' || !smsTo || !smsBody}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'sms' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Send className="w-4 h-4 mr-2" />}
                                Send SMS
                            </Button>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>WhatsApp</CardTitle>
                            <CardDescription>Send WhatsApp messages via Twilio</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <p className="text-sm text-gray-500">
                                Use twilioWhatsapp function with same format as SMS
                            </p>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* Email Tab */}
                <TabsContent value="email" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <Mail className="w-5 h-5 text-purple-600" />
                                Send Email
                            </CardTitle>
                            <CardDescription>Send transactional emails using the built-in SendEmail integration</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Input
                                value={emailTo}
                                onChange={(e) => setEmailTo(e.target.value)}
                                placeholder="Recipient email address"
                                type="email"
                            />
                            <Input
                                value={emailSubject}
                                onChange={(e) => setEmailSubject(e.target.value)}
                                placeholder="Email subject"
                            />
                            <Textarea
                                value={emailBody}
                                onChange={(e) => setEmailBody(e.target.value)}
                                placeholder="Email body..."
                                className="min-h-[100px]"
                            />
                            <Button
                                onClick={async () => {
                                    setLoading('email');
                                    setResult(null);
                                    try {
                                        const response = await base44.integrations.Core.SendEmail({
                                            to: emailTo,
                                            subject: emailSubject,
                                            body: emailBody
                                        });
                                        setResult({ success: true, data: response });
                                    } catch (error) {
                                        setResult({ success: false, error: error.message });
                                    } finally {
                                        setLoading('');
                                    }
                                }}
                                disabled={loading === 'email' || !emailTo || !emailSubject || !emailBody}
                                className="bg-purple-600 hover:bg-purple-700"
                            >
                                {loading === 'email' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Send className="w-4 h-4 mr-2" />}
                                Send Email
                            </Button>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* PDF Tab */}
                <TabsContent value="pdf" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle>Generate PDF</CardTitle>
                            <CardDescription>Create reports, invoices, and tables</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <Input
                                value={pdfTitle}
                                onChange={(e) => setPdfTitle(e.target.value)}
                                placeholder="Document title"
                            />
                            <Textarea
                                value={pdfContent}
                                onChange={(e) => setPdfContent(e.target.value)}
                                placeholder="Document content..."
                                className="min-h-[100px]"
                            />
                            <div className="flex gap-2">
                                <Button
                                    onClick={async () => {
                                        setLoading('pdf');
                                        try {
                                            const response = await base44.functions.invoke('generatePdf', { 
                                                type: 'report',
                                                title: pdfTitle,
                                                content: pdfContent
                                            });
                                            const blob = new Blob([response.data], { type: 'application/pdf' });
                                            const url = window.URL.createObjectURL(blob);
                                            const a = document.createElement('a');
                                            a.href = url;
                                            a.download = `${pdfTitle}.pdf`;
                                            a.click();
                                            setResult({ success: true, data: 'PDF downloaded!' });
                                        } catch (error) {
                                            setResult({ success: false, error: error.message });
                                        } finally {
                                            setLoading('');
                                        }
                                    }}
                                    disabled={loading === 'pdf'}
                                    className="bg-purple-600 hover:bg-purple-700"
                                >
                                    {loading === 'pdf' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <FileText className="w-4 h-4 mr-2" />}
                                    Generate Report PDF
                                </Button>
                                <Button
                                    onClick={async () => {
                                        setLoading('invoice');
                                        try {
                                            const response = await base44.functions.invoke('generatePdf', { 
                                                type: 'invoice',
                                                title: 'Invoice',
                                                data: {
                                                    invoiceNumber: 'INV-001',
                                                    date: new Date().toLocaleDateString(),
                                                    dueDate: new Date(Date.now() + 30*24*60*60*1000).toLocaleDateString(),
                                                    billTo: { name: 'John Doe', address: '123 Main St', email: 'john@example.com' },
                                                    items: [
                                                        { description: 'Consulting Services', quantity: 10, price: 150 },
                                                        { description: 'Development Work', quantity: 20, price: 100 }
                                                    ]
                                                }
                                            });
                                            const blob = new Blob([response.data], { type: 'application/pdf' });
                                            const url = window.URL.createObjectURL(blob);
                                            const a = document.createElement('a');
                                            a.href = url;
                                            a.download = 'invoice.pdf';
                                            a.click();
                                            setResult({ success: true, data: 'Invoice PDF downloaded!' });
                                        } catch (error) {
                                            setResult({ success: false, error: error.message });
                                        } finally {
                                            setLoading('');
                                        }
                                    }}
                                    disabled={loading === 'invoice'}
                                    variant="outline"
                                >
                                    {loading === 'invoice' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                                    Generate Invoice
                                </Button>
                            </div>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* Export Tab */}
                <TabsContent value="export" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle>Data Export</CardTitle>
                            <CardDescription>Export data to CSV, Excel, or JSON</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="flex gap-2">
                                <Button
                                    onClick={async () => {
                                        setLoading('csv');
                                        try {
                                            const response = await base44.functions.invoke('exportData', { 
                                                format: 'csv',
                                                filename: 'sample-export',
                                                data: [
                                                    { name: 'Product A', price: 29.99, quantity: 100 },
                                                    { name: 'Product B', price: 49.99, quantity: 50 },
                                                    { name: 'Product C', price: 19.99, quantity: 200 }
                                                ]
                                            });
                                            const blob = new Blob([response.data], { type: 'text/csv' });
                                            const url = window.URL.createObjectURL(blob);
                                            const a = document.createElement('a');
                                            a.href = url;
                                            a.download = 'sample-export.csv';
                                            a.click();
                                            setResult({ success: true, data: 'CSV downloaded!' });
                                        } catch (error) {
                                            setResult({ success: false, error: error.message });
                                        } finally {
                                            setLoading('');
                                        }
                                    }}
                                    disabled={loading === 'csv'}
                                    className="bg-purple-600 hover:bg-purple-700"
                                >
                                    {loading === 'csv' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Download className="w-4 h-4 mr-2" />}
                                    Export to CSV
                                </Button>
                                <Button
                                    onClick={async () => {
                                        setLoading('excel');
                                        try {
                                            const response = await base44.functions.invoke('exportData', { 
                                                format: 'excel',
                                                filename: 'sample-export',
                                                sheetName: 'Products',
                                                data: [
                                                    { name: 'Product A', price: 29.99, quantity: 100 },
                                                    { name: 'Product B', price: 49.99, quantity: 50 },
                                                    { name: 'Product C', price: 19.99, quantity: 200 }
                                                ]
                                            });
                                            const blob = new Blob([response.data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
                                            const url = window.URL.createObjectURL(blob);
                                            const a = document.createElement('a');
                                            a.href = url;
                                            a.download = 'sample-export.xlsx';
                                            a.click();
                                            setResult({ success: true, data: 'Excel downloaded!' });
                                        } catch (error) {
                                            setResult({ success: false, error: error.message });
                                        } finally {
                                            setLoading('');
                                        }
                                    }}
                                    disabled={loading === 'excel'}
                                    variant="outline"
                                >
                                    {loading === 'excel' ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                                    Export to Excel
                                </Button>
                            </div>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* Webhooks Tab */}
                <TabsContent value="webhook" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle>Webhook Handler</CardTitle>
                            <CardDescription>Receive and process webhooks from external services</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="bg-gray-100 rounded-lg p-4 font-mono text-sm">
                                <p className="text-gray-600 mb-2">Webhook URL:</p>
                                <p className="text-purple-600 break-all">[Your App URL]/functions/webhookHandler?secret=YOUR_SECRET</p>
                            </div>
                            <p className="text-sm text-gray-500 mt-4">
                                Configure your external services to send webhooks to this URL. 
                                The handler supports JSON, form-urlencoded, and raw text payloads.
                            </p>
                        </CardContent>
                    </Card>
                </TabsContent>

                {/* Users Tab */}
                <TabsContent value="users" className="space-y-4">
                    <Card>
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <UserPlus className="w-5 h-5 text-purple-600" />
                                Share Your App
                            </CardTitle>
                            <CardDescription>Invite users to access your 1cPublishing app</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
                                <p className="text-amber-800 text-sm">
                                    <strong>Note:</strong> User invitations must be sent from the Base44 dashboard. 
                                    Click the <strong>"Share"</strong> button in the top-right corner of the dashboard to invite users.
                                </p>
                            </div>
                            
                            <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                                <h4 className="font-medium text-gray-900 mb-4">How to invite users:</h4>
                                <ol className="list-decimal list-inside space-y-2 text-gray-600">
                                    <li>Go to the Base44 dashboard</li>
                                    <li>Click the <strong>"Share"</strong> button in the top-right</li>
                                    <li>Enter the user's email address</li>
                                    <li>Select the access level (User or Admin)</li>
                                    <li>Click "Send Invitation"</li>
                                </ol>
                            </div>

                            <div className="mt-6">
                                <h4 className="font-medium text-gray-900 mb-2">Public Access URL:</h4>
                                <div className="bg-gray-100 rounded-lg p-3 font-mono text-sm text-purple-600">
                                    https://1cpublishing.com
                                </div>
                                <p className="text-xs text-gray-500 mt-1">Anyone with this link can access your app</p>
                            </div>
                        </CardContent>
                    </Card>
                </TabsContent>
            </Tabs>

            {/* Results Panel */}
            {result && (
                <Card className="mt-6">
                    <CardHeader className="flex flex-row items-center justify-between">
                        <CardTitle className="flex items-center gap-2">
                            {result.success ? (
                                <Check className="w-5 h-5 text-green-500" />
                            ) : (
                                <span className="text-red-500">✕</span>
                            )}
                            Result
                        </CardTitle>
                        <Button variant="ghost" size="sm" onClick={copyResult}>
                            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                        </Button>
                    </CardHeader>
                    <CardContent>
                        <pre className="bg-gray-100 rounded-lg p-4 overflow-auto max-h-[300px] text-sm">
                            {JSON.stringify(result, null, 2)}
                        </pre>
                    </CardContent>
                </Card>
            )}
        </div>
    );
}